name: Manage GitHub Access Based on Subscription Plan

on:
  repository_dispatch:
    types: [webhook_event]

jobs:
  manage-access:
    runs-on: ubuntu-latest

    env:
      # Define premium repositories here
      PREMIUM_REPOS: "premium-repo another-repo third-repo"

    steps:
      - name: Determine Event Type and Manage Access
        env:
          GITHUB_USERNAME: "${{ github.event.client_payload.github_username }}"
          LINE_ITEMS_JSON: "${{ toJson(github.event.client_payload.line_items) }}"
        run: |
          echo "Github username: $GITHUB_USERNAME"

          # Check if LINE_ITEMS_JSON is populated correctly
          if [ -z "$LINE_ITEMS_JSON" ]; then
            echo "Error: LINE_ITEMS_JSON is empty"
            exit 1
          else
            echo "Line items JSON: $LINE_ITEMS_JSON"
          fi

          # Validate JSON structure before processing
          if echo "$LINE_ITEMS_JSON" | jq empty; then
            echo "JSON structure is valid."
          else
            echo "Error: Invalid JSON structure in LINE_ITEMS_JSON"
            exit 1
          fi

          # Process each line item in the JSON array
          echo "$LINE_ITEMS_JSON" | jq -c '.[]' | while read -r ITEM; do
            ITEM_NAME=$(echo "$ITEM" | jq -r '.name')
            echo "Processing item: $ITEM_NAME"

            if [[ "$ITEM_NAME" == "Basic Module" ]]; then
              echo "Granting access to basic repositories..."
              curl -L \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ACCESS_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/SaaSBerryIO/saasberry-ui/collaborators/$GITHUB_USERNAME \
                -d '{"permission":"pull"}'

            elif [[ "$ITEM_NAME" == "Premium Module" ]]; then
              echo "Granting access to premium repositories..."

              # Loop through each premium repository
              for REPO in $PREMIUM_REPOS; do
                echo "Granting access to $REPO..."
                curl -L \
                  -X PUT \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.ORG_ACCESS_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/SaaSBerryIO/$REPO/collaborators/$GITHUB_USERNAME \
                  -d '{"permission":"pull"}'
              done

            else
              echo "Unknown subscription item: $ITEM_NAME"
            fi
          done
